import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code } from "next/font/google";

const fira_Code = Fira_Code({
  subsets: ["latin"],
  variable: "--fira_code",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fira_Code.variable} antialiased bg-[#292C37] text-white `}
      >
        {children}
      </body>
    </html>
  );
}
